services:
  web:
    build: .
    env_file:
    - .env

    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
    - db
    volumes:
    - ./static/uploads:/app/static/uploads

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: