"""corrigindo bug

Revision ID: 5fd8e395b931
Revises: 
Create Date: 2026-05-24 19:06:29.731331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd8e395b931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint(batch_op.f('organization_img_path_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['img_id'])
        batch_op.drop_constraint(batch_op.f('organization_img_path_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'image', ['img_id'], ['id'])
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('organization_img_path_fkey'), 'image', ['img_path'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('organization_img_path_key'), ['img_path'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('img_id')

    # ### end Alembic commands ###
