"""corrigindo member v2

Revision ID: dde54460165b
Revises: 5fd8e395b931
Create Date: 2026-05-24 19:11:43.017081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde54460165b'
down_revision = '5fd8e395b931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
