"""criando created_at e melhorias nos models

Revision ID: e0dbf717fb53
Revises: b6da8884b49d
Create Date: 2026-05-22 11:31:35.966575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dbf717fb53'
down_revision = 'b6da8884b49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks_completed', sa.Integer(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=9), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tasks_completed')

    # ### end Alembic commands ###
